version: '3.8'

services:
  buddy-mobile:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - buddy-network

networks:
  buddy-network:
    driver: bridge 